name: Fabric CICD
on:
 push:
   branches:
     - test
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Setup Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'
     - name: Install Dependencies
       run: |
         pip install --upgrade pip
         pip install fabric-cicd msal python-dotenv
     - name: Azure Login
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         allow-no-subscriptions: true
     - name: Run Deployment
       run: python deployment.py
       env:
         TEST_WORKSPACE_ID: ${{ secrets.TEST_WORKSPACE_ID }}
